const eslintConfigPrettier = require('eslint-config-prettier');

module.exports = [
  {
    ignores: [
      'node_modules/**',
      'assets/vendor/**',
      'Projekte/**',
      'test-results/**',
      'playwright-report/**',
      'assets/js/projects_data.js',
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        URLSearchParams: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        module: 'readonly',
        require: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        Buffer: 'readonly',
        Event: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        Node: 'readonly',
        Prism: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        history: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        performance: 'readonly',
        cancelAnimationFrame: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        HTMLImageElement: 'readonly',
        clients: 'readonly',
        // Cross-file browser globals. Classic <script> includes define them in the shared
        // global scope (constants.js: APP, STORAGE_KEYS; components.js: AppStorage;
        // news_data.js: newsData; toast.js: showToast), and three ES modules attach
        // themselves to window so those classic scripts can reach them
        // (modules/game-audio.js, modules/achievements.js, modules/confetti.js).
        APP: 'readonly',
        AppStorage: 'readonly',
        STORAGE_KEYS: 'readonly',
        GameAudio: 'readonly',
        Achievements: 'readonly',
        Confetti: 'readonly',
        newsData: 'readonly',
        initBlogEnhancements: 'readonly',
        showToast: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['error', { args: 'none', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-empty': 'warn',
      'no-console': 'off',
    },
  },
  eslintConfigPrettier,
];
