const eslintConfigPrettier = require('eslint-config-prettier');

module.exports = [
  {
    ignores: [
      'node_modules/**',
      'assets/vendor/**',
      'Projekte/**',
      'test-results/**',
      'playwright-report/**',
      'assets/js/projects_data.js',
    ],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        CustomEvent: 'readonly',
        URLSearchParams: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        module: 'readonly',
        require: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        Buffer: 'readonly',
        Event: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        Node: 'readonly',
        Prism: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        alert: 'readonly',
        performance: 'readonly',
        cancelAnimationFrame: 'readonly',
        // Cross-file browser globals defined by non-module <script> includes
        // (constants.js, storage.js, audio.js, achievements.js, confetti.js, news_data.js …)
        APP: 'readonly',
        StorageManager: 'readonly',
        STORAGE_KEYS: 'readonly',
        GameAudio: 'readonly',
        Achievements: 'readonly',
        Confetti: 'readonly',
        newsData: 'readonly',
        initBlogEnhancements: 'readonly',
        showToast: 'readonly',
        BoundingBoxRenderer: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
      'no-undef': 'warn',
      'no-empty': 'warn',
      'no-console': 'off',
    },
  },
  eslintConfigPrettier,
];
