import React, { useState } from 'react';
import { Cloud, Server, Database, Code } from 'lucide-react';

export default function CloudDesignerLab({ onRewardXP }) {
  const components = [
    { id: 'vpc', name: 'AWS VPC (Virtual Private Cloud)', type: 'network', active: true },
    { id: 'ec2', name: 'EC2 Compute Node (App)', type: 'compute', active: true },
    { id: 'rds', name: 'RDS PostgreSQL Database', type: 'database', active: true }
  ];

  const [generatedTerraform, setGeneratedTerraform] = useState('');

  const generateTerraformCode = () => {
    const tf = `# Terraform Cloud Infrastructure Architecture (Generated by IT-DevGame)
provider "aws" {
  region = "eu-central-1"
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  tags = { Name = "DevGame-VPC" }
}

resource "aws_instance" "app_server" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.micro"
  subnet_id     = aws_vpc.main.id
}

resource "aws_db_instance" "database" {
  allocated_storage    = 20
  engine               = "postgres"
  instance_class       = "db.t3.micro"
  username             = "admin"
  password             = "SecurePassword123!"
}`;
    setGeneratedTerraform(tf);
    if (onRewardXP) onRewardXP(30);
  };

  return (
    <div style={{ background: 'var(--bg-card)', padding: '28px', borderRadius: 'var(--radius-xl)', border: '1px solid var(--border-color)' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <span className="badge badge-indigo" style={{ marginBottom: '8px' }}>
            <Cloud size={14} /> Cloud Native & DevOps (AWS / IaC)
          </span>
          <h2 style={{ fontSize: '1.8rem', fontWeight: '800', margin: '4px 0', color: 'var(--text-main)' }}>
            ☁️ Cloud Infrastructure & Terraform IaC Designer
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.95rem' }}>
            Designe Cloud-Architekturen und generiere echten Terraform Code (Infrastructure as Code).
          </p>
        </div>
      </div>

      {/* Cloud Components Canvas */}
      <div style={{ background: '#0f172a', padding: '32px', borderRadius: 'var(--radius-lg)', marginBottom: '24px', display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
        {components.map((comp) => (
          <div key={comp.id} style={{ background: '#1e293b', border: '2px solid #38bdf8', padding: '20px', borderRadius: '12px', minWidth: '220px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px' }}>
              {comp.type === 'compute' && <Server color="#38bdf8" />}
              {comp.type === 'database' && <Database color="#10b981" />}
              {comp.type === 'network' && <Cloud color="#a855f7" />}
              <span style={{ color: '#fff', fontWeight: '700' }}>{comp.name}</span>
            </div>
            <span className="badge badge-indigo" style={{ fontSize: '0.75rem' }}>{comp.type.toUpperCase()}</span>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: '16px', marginBottom: '24px' }}>
        <button className="btn btn-primary" onClick={generateTerraformCode}>
          <Code size={16} /> Terraform Code (main.tf) Generieren
        </button>
      </div>

      {generatedTerraform && (
        <div className="code-window">
          <div className="code-header" style={{ background: '#1e293b', padding: '12px 16px', color: '#38bdf8' }}>
            <span>main.tf (HCL HashiCorp Language)</span>
          </div>
          <pre style={{ background: '#090d16', color: '#38bdf8', padding: '16px', borderRadius: '0 0 var(--radius-lg) var(--radius-lg)', margin: 0, overflowX: 'auto', fontFamily: 'monospace' }}>
            {generatedTerraform}
          </pre>
        </div>
      )}
    </div>
  );
}
